export const EventType = {

    //创建角色列表的part选择背景
    CHANGE_ROLE_PART_SELECT: 'CHANGE_ROLE_PART_SELECT',

    SEND_CAT_ACTION:"SEND_CAT_ACTION", //猫咪动作的事件
    SEND_BUY_SHOP_ITEM_SUCCESS_INFO:"SEND_BUY_SHOP_ITEM_INFO", //购买成功后的消息

    LOGIN_COMPELETED: "LOGIN_COMPELETED",


    PLAYER_KUANG_SELECT: "PLAYER_KUANG_SELECT",
    UPDTAE_PLAYER_KUANG: "UPDTAE_PLAYER_INFO",//更换刷新头像框

    UPDATE_ROLE_PLAY_INDEX: "UPDATE_ROLE_PLAY_INDEX", //更换人物部分的icon数组

    //显示对话记录按钮
    SHOW_CHAT_LOG_BUTTON:"UPDATE_GUIDE_INFO_WORK_PAGE",

    //显示打工按钮
    SHOW_WORK_BUTTON:"SHOW_WORK_BUTTON",

    //更新打工页引导信息
    UPDATE_GUIDE_INFO_WORK_PAGE:"UPDATE_GUIDE_INFO_WORK_PAGE",

    //更新首页引导信息
    UPDATE_GUIDE_INFO_MAIN_VIEW:"UPDATE_GUIDE_INFO_MAIN_VIEW",

    //更新好感度
    UPDATE_CAT_CV:"UPDATE_CAT_CV",

    //开始打工
    START_CAT_WORK:"START_CAT_WORK",

    //打工结果
    WORK_STATE_INFO:"WORK_STATE_INFO",

    //打工失败
    WORK_DEFAULT:"WORK_DEFAULT",

    FRESH_GAMELOCKED:"FRESH_GAMELOCKED",//锁定游戏
    FRESH_RENWU_REGE:"FRESH_RENWU_REGE",

    FRESH_CHUANDI_ZS:"FRESH_CHUANDI_ZS",

    //=============socket===============
    SOCKET_ONOPEN:"SOCKET_ONOPEN",
    SOCKET_ONMESSAGE:"SOCKET_ONMESSAGE",
    SOCKET_ONCLOSE:"SOCKET_ONCLOSE",
    SOCKET_ONERROR:"SOCKET_ONERROR",
    
    SOCKET_GETALL_NPCS:"SOCKET_GETALL_NPCS",//查询所有NPC
    SOCKET_ONLINE_NPCS:"SOCKET_ONLINE_NPCS",//上线NPC
    SOCKET_OFFLINE_NPCS:"SOCKET_OFFLINE_NPCS",//下线NPC

    SOCKET_NPC_MOVE:"SOCKET_NPC_MOVE",//下线NPC

    SOCKET_NPC_ACTION:"SOCKET_NPC_ACTION",//NPC action

    OBJECT_STATE_CHANGE:"OBJECT_STATE_CHANGE",//NPC action

    SOCKET_ITEM_STATE_CHANGE:"SOCKET_ITEM_STATE_CHANGE",//NPC action

    SOCKET_SELECT_CATS:"SOCKET_SELECT_CATS",
    SOCKET_CHANGE_CATS:"SOCKET_CHANGE_CATS",
    SOCKET_CHANGEINFO_CATS:"SOCKET_CHANGEINFO_CATS10004",
    SOCKET_CHECK_PLAYERITEMS:"SOCKET_CHECK_PLAYERITEMS",
    SOCKET_CHAT:"SOCKET_CHAT",
    SOCKET_CHATLIST:"SOCKET_CHATLIST",
    SOCKET_TASKLIST:"SOCKET_TASKLIST",
    SOCKET_TASK_CHANGE:"SOCKET_TASK_CHANGE",
    SOCKET_TASK_GET:"SOCKET_TASK_GET",
    SOCKET_SHARE:"SOCKET_SHARE",
    SOCKET_QIANDAO:"SOCKET_QISNANDAO",
    SOCKET_ITEMUPDATE:"SOCKET_ITEMUPDATE_10009",
    SOCKET_CHANGE_CATSDATA:"SOCKET_CHANGE_CATSDATA",
    SOCKET_ZHAOHU:"SOCKET_ZHAOHU",
    //=============shop=========================
    SOCKET_MOVE:"SOCKET_MOVE",
    //玩具列表
    SOCKET_TOY_LIST:"SOCKET_TOY_LIST",
    

}