
logging:
  config: classpath:logcfg-dev.xml

server:
  port: 8280
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/aitown?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useOldAliasMetadataBehavior=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: Enc(ktG2/hznParxqw6NNUndwA==)
    password: Enc(sEo79y08949iMY+8lbF4iw==)
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 200
      auto-commit: true
      idle-timeout: 60000
      pool-name: HikariCP
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      validation-timeout: 60000
      login-timeout: 5
      register-mbeans: true

  #redis
  redis:
    host: 127.0.0.1
    password: Enc(Dc/18Ir5VOzTFPjvQ8ff2w==)
    port: 6379
    database: 3
    timeout: 3000
    jedis:
      pool:
        max-idle: 20
        min-idle: 2
        max-wait: 2000
        max-active: 64
  #Redisson配置
  redisson:
    enable: true
    transportMode: NIO
    threads: 4
    nettyThreads: 4
    codec:
      class: org.redisson.codec.JsonJacksonCodec
    singleServerConfig:
      address: ${spring.redis.host}
      password: ${spring.redis.password}
      port: ${spring.redis.port}
      # 连接空闲超时，单位：毫秒
      idleConnectionTimeout: 10000
      # 连接超时，单位：毫秒
      connectTimeout: 30000
      # 命令等待超时，单位：毫秒
      timeout: 30000
      retryAttempts: 1
      # 命令重试发送时间间隔，单位：毫秒
      retryInterval: 1500
      # 单个连接最大订阅数量
      subscriptionsPerConnection: 5
      # 客户端名称
      clientName: gms-server
      # 发布和订阅连接的最小空闲连接数
      subscriptionConnectionMinimumIdleSize: 1
      # 发布和订阅连接池大小
      subscriptionConnectionPoolSize: 50
      # 最小空闲连接数
      connectionMinimumIdleSize: 32
      # 连接池大小
      connectionPoolSize: 64
      # DNS监测时间间隔，单位：毫秒
      dnsMonitoringInterval: 5000