logging:
  config: classpath:logcfg-dev.xml

server:
  port: 8888
  servlet:
    # 应用的访问路径
    context-path: /
  #address: 0.0.0.0
  # SSL证书设置
  #ssl:
  #  key-store: classpath:privkey.p12
  #  key-store-password: ws2024
  #  keyStoreType: PKCS12
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cat?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useOldAliasMetadataBehavior=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 200
      auto-commit: true
      idle-timeout: 60000
      pool-name: HikariCP
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      validation-timeout: 60000
      login-timeout: 5
      register-mbeans: true

proxy:
  http:
    host:
    port:


telegram:
  bot:
    botUserName: wuji2024_bot
    botToken: 6962037670:AAHseRwquOdt1OvtpV05Iv46AXJqZHEpEKs
    webHookPath: https://cat.infinitytest.cc/api/tg/
    gameUrl: https://cat.infinitytest.cc/
    gameName: HaHaCatAcademia
    tgUrl: https://cat.infinitytest.cc/api/tg/
    defaultSrc: TG
