// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: header.proto

package com.infinity.protocol;

public final class HeaderOuterClass {
  private HeaderOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HeaderOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.infinity.protocol.Header)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 请求的类型
     * </pre>
     *
     * <code>string rtype = 1;</code>
     */
    String getRtype();
    /**
     * <pre>
     * 请求的类型
     * </pre>
     *
     * <code>string rtype = 1;</code>
     */
    com.google.protobuf.ByteString
        getRtypeBytes();

    /**
     * <pre>
     * 命令号
     * </pre>
     *
     * <code>int32 command = 2;</code>
     */
    int getCommand();

    /**
     * <pre>
     * 原地址
     * </pre>
     *
     * <code>string source = 3;</code>
     */
    String getSource();
    /**
     * <pre>
     * 原地址
     * </pre>
     *
     * <code>string source = 3;</code>
     */
    com.google.protobuf.ByteString
        getSourceBytes();

    /**
     * <pre>
     * 目标地址
     * </pre>
     *
     * <code>string destination = 4;</code>
     */
    String getDestination();
    /**
     * <pre>
     * 目标地址
     * </pre>
     *
     * <code>string destination = 4;</code>
     */
    com.google.protobuf.ByteString
        getDestinationBytes();

    /**
     * <pre>
     * 扩展数据，可选
     * </pre>
     *
     * <code>bytes padding = 5;</code>
     */
    com.google.protobuf.ByteString getPadding();

    /**
     * <pre>
     * 错误码
     * </pre>
     *
     * <code>int32 code = 6;</code>
     */
    int getCode();

    /**
     * <pre>
     *范围（dst为节点类型时有效） 0随机1个， 1所有
     * </pre>
     *
     * <code>int32 dstScope = 7;</code>
     */
    int getDstScope();

    /**
     * <pre>
     *子命令
     * </pre>
     *
     * <code>int32 cmd = 8;</code>
     */
    int getCmd();
  }
  /**
   * Protobuf type {@code com.infinity.protocol.Header}
   */
  public  static final class Header extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.infinity.protocol.Header)
      HeaderOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Header.newBuilder() to construct.
    private Header(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Header() {
      rtype_ = "";
      source_ = "";
      destination_ = "";
      padding_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Header();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Header(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              rtype_ = s;
              break;
            }
            case 16: {

              command_ = input.readInt32();
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              source_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              destination_ = s;
              break;
            }
            case 42: {

              padding_ = input.readBytes();
              break;
            }
            case 48: {

              code_ = input.readInt32();
              break;
            }
            case 56: {

              dstScope_ = input.readInt32();
              break;
            }
            case 64: {

              cmd_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return HeaderOuterClass.internal_static_com_infinity_protocol_Header_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return HeaderOuterClass.internal_static_com_infinity_protocol_Header_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Header.class, Builder.class);
    }

    public static final int RTYPE_FIELD_NUMBER = 1;
    private volatile Object rtype_;
    /**
     * <pre>
     * 请求的类型
     * </pre>
     *
     * <code>string rtype = 1;</code>
     */
    public String getRtype() {
      Object ref = rtype_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        rtype_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 请求的类型
     * </pre>
     *
     * <code>string rtype = 1;</code>
     */
    public com.google.protobuf.ByteString
        getRtypeBytes() {
      Object ref = rtype_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        rtype_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMAND_FIELD_NUMBER = 2;
    private int command_;
    /**
     * <pre>
     * 命令号
     * </pre>
     *
     * <code>int32 command = 2;</code>
     */
    public int getCommand() {
      return command_;
    }

    public static final int SOURCE_FIELD_NUMBER = 3;
    private volatile Object source_;
    /**
     * <pre>
     * 原地址
     * </pre>
     *
     * <code>string source = 3;</code>
     */
    public String getSource() {
      Object ref = source_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        source_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 原地址
     * </pre>
     *
     * <code>string source = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSourceBytes() {
      Object ref = source_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        source_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESTINATION_FIELD_NUMBER = 4;
    private volatile Object destination_;
    /**
     * <pre>
     * 目标地址
     * </pre>
     *
     * <code>string destination = 4;</code>
     */
    public String getDestination() {
      Object ref = destination_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        destination_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 目标地址
     * </pre>
     *
     * <code>string destination = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationBytes() {
      Object ref = destination_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        destination_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PADDING_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString padding_;
    /**
     * <pre>
     * 扩展数据，可选
     * </pre>
     *
     * <code>bytes padding = 5;</code>
     */
    public com.google.protobuf.ByteString getPadding() {
      return padding_;
    }

    public static final int CODE_FIELD_NUMBER = 6;
    private int code_;
    /**
     * <pre>
     * 错误码
     * </pre>
     *
     * <code>int32 code = 6;</code>
     */
    public int getCode() {
      return code_;
    }

    public static final int DSTSCOPE_FIELD_NUMBER = 7;
    private int dstScope_;
    /**
     * <pre>
     *范围（dst为节点类型时有效） 0随机1个， 1所有
     * </pre>
     *
     * <code>int32 dstScope = 7;</code>
     */
    public int getDstScope() {
      return dstScope_;
    }

    public static final int CMD_FIELD_NUMBER = 8;
    private int cmd_;
    /**
     * <pre>
     *子命令
     * </pre>
     *
     * <code>int32 cmd = 8;</code>
     */
    public int getCmd() {
      return cmd_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getRtypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, rtype_);
      }
      if (command_ != 0) {
        output.writeInt32(2, command_);
      }
      if (!getSourceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, source_);
      }
      if (!getDestinationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, destination_);
      }
      if (!padding_.isEmpty()) {
        output.writeBytes(5, padding_);
      }
      if (code_ != 0) {
        output.writeInt32(6, code_);
      }
      if (dstScope_ != 0) {
        output.writeInt32(7, dstScope_);
      }
      if (cmd_ != 0) {
        output.writeInt32(8, cmd_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getRtypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, rtype_);
      }
      if (command_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, command_);
      }
      if (!getSourceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, source_);
      }
      if (!getDestinationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, destination_);
      }
      if (!padding_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, padding_);
      }
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, code_);
      }
      if (dstScope_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, dstScope_);
      }
      if (cmd_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, cmd_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Header)) {
        return super.equals(obj);
      }
      Header other = (Header) obj;

      if (!getRtype()
          .equals(other.getRtype())) return false;
      if (getCommand()
          != other.getCommand()) return false;
      if (!getSource()
          .equals(other.getSource())) return false;
      if (!getDestination()
          .equals(other.getDestination())) return false;
      if (!getPadding()
          .equals(other.getPadding())) return false;
      if (getCode()
          != other.getCode()) return false;
      if (getDstScope()
          != other.getDstScope()) return false;
      if (getCmd()
          != other.getCmd()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getRtype().hashCode();
      hash = (37 * hash) + COMMAND_FIELD_NUMBER;
      hash = (53 * hash) + getCommand();
      hash = (37 * hash) + SOURCE_FIELD_NUMBER;
      hash = (53 * hash) + getSource().hashCode();
      hash = (37 * hash) + DESTINATION_FIELD_NUMBER;
      hash = (53 * hash) + getDestination().hashCode();
      hash = (37 * hash) + PADDING_FIELD_NUMBER;
      hash = (53 * hash) + getPadding().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + DSTSCOPE_FIELD_NUMBER;
      hash = (53 * hash) + getDstScope();
      hash = (37 * hash) + CMD_FIELD_NUMBER;
      hash = (53 * hash) + getCmd();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Header parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Header parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Header prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.infinity.protocol.Header}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.infinity.protocol.Header)
        HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return HeaderOuterClass.internal_static_com_infinity_protocol_Header_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return HeaderOuterClass.internal_static_com_infinity_protocol_Header_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Header.class, Builder.class);
      }

      // Construct using com.infinity.protocol.HeaderOuterClass.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        rtype_ = "";

        command_ = 0;

        source_ = "";

        destination_ = "";

        padding_ = com.google.protobuf.ByteString.EMPTY;

        code_ = 0;

        dstScope_ = 0;

        cmd_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return HeaderOuterClass.internal_static_com_infinity_protocol_Header_descriptor;
      }

      @Override
      public Header getDefaultInstanceForType() {
        return Header.getDefaultInstance();
      }

      @Override
      public Header build() {
        Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Header buildPartial() {
        Header result = new Header(this);
        result.rtype_ = rtype_;
        result.command_ = command_;
        result.source_ = source_;
        result.destination_ = destination_;
        result.padding_ = padding_;
        result.code_ = code_;
        result.dstScope_ = dstScope_;
        result.cmd_ = cmd_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Header) {
          return mergeFrom((Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Header other) {
        if (other == Header.getDefaultInstance()) return this;
        if (!other.getRtype().isEmpty()) {
          rtype_ = other.rtype_;
          onChanged();
        }
        if (other.getCommand() != 0) {
          setCommand(other.getCommand());
        }
        if (!other.getSource().isEmpty()) {
          source_ = other.source_;
          onChanged();
        }
        if (!other.getDestination().isEmpty()) {
          destination_ = other.destination_;
          onChanged();
        }
        if (other.getPadding() != com.google.protobuf.ByteString.EMPTY) {
          setPadding(other.getPadding());
        }
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (other.getDstScope() != 0) {
          setDstScope(other.getDstScope());
        }
        if (other.getCmd() != 0) {
          setCmd(other.getCmd());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Header parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Header) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object rtype_ = "";
      /**
       * <pre>
       * 请求的类型
       * </pre>
       *
       * <code>string rtype = 1;</code>
       */
      public String getRtype() {
        Object ref = rtype_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          rtype_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 请求的类型
       * </pre>
       *
       * <code>string rtype = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRtypeBytes() {
        Object ref = rtype_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          rtype_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 请求的类型
       * </pre>
       *
       * <code>string rtype = 1;</code>
       */
      public Builder setRtype(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rtype_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求的类型
       * </pre>
       *
       * <code>string rtype = 1;</code>
       */
      public Builder clearRtype() {
        
        rtype_ = getDefaultInstance().getRtype();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求的类型
       * </pre>
       *
       * <code>string rtype = 1;</code>
       */
      public Builder setRtypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rtype_ = value;
        onChanged();
        return this;
      }

      private int command_ ;
      /**
       * <pre>
       * 命令号
       * </pre>
       *
       * <code>int32 command = 2;</code>
       */
      public int getCommand() {
        return command_;
      }
      /**
       * <pre>
       * 命令号
       * </pre>
       *
       * <code>int32 command = 2;</code>
       */
      public Builder setCommand(int value) {
        
        command_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 命令号
       * </pre>
       *
       * <code>int32 command = 2;</code>
       */
      public Builder clearCommand() {
        
        command_ = 0;
        onChanged();
        return this;
      }

      private Object source_ = "";
      /**
       * <pre>
       * 原地址
       * </pre>
       *
       * <code>string source = 3;</code>
       */
      public String getSource() {
        Object ref = source_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          source_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 原地址
       * </pre>
       *
       * <code>string source = 3;</code>
       */
      public com.google.protobuf.ByteString
          getSourceBytes() {
        Object ref = source_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          source_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 原地址
       * </pre>
       *
       * <code>string source = 3;</code>
       */
      public Builder setSource(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 原地址
       * </pre>
       *
       * <code>string source = 3;</code>
       */
      public Builder clearSource() {
        
        source_ = getDefaultInstance().getSource();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 原地址
       * </pre>
       *
       * <code>string source = 3;</code>
       */
      public Builder setSourceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        source_ = value;
        onChanged();
        return this;
      }

      private Object destination_ = "";
      /**
       * <pre>
       * 目标地址
       * </pre>
       *
       * <code>string destination = 4;</code>
       */
      public String getDestination() {
        Object ref = destination_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          destination_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       * 目标地址
       * </pre>
       *
       * <code>string destination = 4;</code>
       */
      public com.google.protobuf.ByteString
          getDestinationBytes() {
        Object ref = destination_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          destination_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 目标地址
       * </pre>
       *
       * <code>string destination = 4;</code>
       */
      public Builder setDestination(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        destination_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 目标地址
       * </pre>
       *
       * <code>string destination = 4;</code>
       */
      public Builder clearDestination() {
        
        destination_ = getDefaultInstance().getDestination();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 目标地址
       * </pre>
       *
       * <code>string destination = 4;</code>
       */
      public Builder setDestinationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        destination_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString padding_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * 扩展数据，可选
       * </pre>
       *
       * <code>bytes padding = 5;</code>
       */
      public com.google.protobuf.ByteString getPadding() {
        return padding_;
      }
      /**
       * <pre>
       * 扩展数据，可选
       * </pre>
       *
       * <code>bytes padding = 5;</code>
       */
      public Builder setPadding(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        padding_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 扩展数据，可选
       * </pre>
       *
       * <code>bytes padding = 5;</code>
       */
      public Builder clearPadding() {
        
        padding_ = getDefaultInstance().getPadding();
        onChanged();
        return this;
      }

      private int code_ ;
      /**
       * <pre>
       * 错误码
       * </pre>
       *
       * <code>int32 code = 6;</code>
       */
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       * 错误码
       * </pre>
       *
       * <code>int32 code = 6;</code>
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 错误码
       * </pre>
       *
       * <code>int32 code = 6;</code>
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private int dstScope_ ;
      /**
       * <pre>
       *范围（dst为节点类型时有效） 0随机1个， 1所有
       * </pre>
       *
       * <code>int32 dstScope = 7;</code>
       */
      public int getDstScope() {
        return dstScope_;
      }
      /**
       * <pre>
       *范围（dst为节点类型时有效） 0随机1个， 1所有
       * </pre>
       *
       * <code>int32 dstScope = 7;</code>
       */
      public Builder setDstScope(int value) {
        
        dstScope_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *范围（dst为节点类型时有效） 0随机1个， 1所有
       * </pre>
       *
       * <code>int32 dstScope = 7;</code>
       */
      public Builder clearDstScope() {
        
        dstScope_ = 0;
        onChanged();
        return this;
      }

      private int cmd_ ;
      /**
       * <pre>
       *子命令
       * </pre>
       *
       * <code>int32 cmd = 8;</code>
       */
      public int getCmd() {
        return cmd_;
      }
      /**
       * <pre>
       *子命令
       * </pre>
       *
       * <code>int32 cmd = 8;</code>
       */
      public Builder setCmd(int value) {
        
        cmd_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *子命令
       * </pre>
       *
       * <code>int32 cmd = 8;</code>
       */
      public Builder clearCmd() {
        
        cmd_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.infinity.protocol.Header)
    }

    // @@protoc_insertion_point(class_scope:com.infinity.protocol.Header)
    private static final Header DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Header();
    }

    public static Header getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Header>
        PARSER = new com.google.protobuf.AbstractParser<Header>() {
      @Override
      public Header parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Header(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Header> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Header> getParserForType() {
      return PARSER;
    }

    @Override
    public Header getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_infinity_protocol_Header_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_infinity_protocol_Header_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014header.proto\022\025com.infinity.protocol\"\213\001" +
      "\n\006Header\022\r\n\005rtype\030\001 \001(\t\022\017\n\007command\030\002 \001(\005" +
      "\022\016\n\006source\030\003 \001(\t\022\023\n\013destination\030\004 \001(\t\022\017\n" +
      "\007padding\030\005 \001(\014\022\014\n\004code\030\006 \001(\005\022\020\n\010dstScope" +
      "\030\007 \001(\005\022\013\n\003cmd\030\010 \001(\005b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_infinity_protocol_Header_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_infinity_protocol_Header_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_infinity_protocol_Header_descriptor,
        new String[] { "Rtype", "Command", "Source", "Destination", "Padding", "Code", "DstScope", "Cmd", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
