// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.infinity.protocol;

public final class HelloOuterClass {
  private HelloOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface HelloOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.infinity.protocol.Hello)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 当前时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    long getTime();

    /**
     * <pre>
     * 附加信息
     * </pre>
     *
     * <code>repeated int32 attachment = 2;</code>
     */
    java.util.List<java.lang.Integer> getAttachmentList();
    /**
     * <pre>
     * 附加信息
     * </pre>
     *
     * <code>repeated int32 attachment = 2;</code>
     */
    int getAttachmentCount();
    /**
     * <pre>
     * 附加信息
     * </pre>
     *
     * <code>repeated int32 attachment = 2;</code>
     */
    int getAttachment(int index);
  }
  /**
   * Protobuf type {@code com.infinity.protocol.Hello}
   */
  public  static final class Hello extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.infinity.protocol.Hello)
      HelloOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Hello.newBuilder() to construct.
    private Hello(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Hello() {
      attachment_ = emptyIntList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Hello();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Hello(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              time_ = input.readInt64();
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                attachment_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              attachment_.addInt(input.readInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                attachment_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                attachment_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          attachment_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.infinity.protocol.HelloOuterClass.internal_static_com_infinity_protocol_Hello_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.infinity.protocol.HelloOuterClass.internal_static_com_infinity_protocol_Hello_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.infinity.protocol.HelloOuterClass.Hello.class, com.infinity.protocol.HelloOuterClass.Hello.Builder.class);
    }

    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <pre>
     * 当前时间
     * </pre>
     *
     * <code>int64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int ATTACHMENT_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.IntList attachment_;
    /**
     * <pre>
     * 附加信息
     * </pre>
     *
     * <code>repeated int32 attachment = 2;</code>
     */
    public java.util.List<java.lang.Integer>
        getAttachmentList() {
      return attachment_;
    }
    /**
     * <pre>
     * 附加信息
     * </pre>
     *
     * <code>repeated int32 attachment = 2;</code>
     */
    public int getAttachmentCount() {
      return attachment_.size();
    }
    /**
     * <pre>
     * 附加信息
     * </pre>
     *
     * <code>repeated int32 attachment = 2;</code>
     */
    public int getAttachment(int index) {
      return attachment_.getInt(index);
    }
    private int attachmentMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (time_ != 0L) {
        output.writeInt64(1, time_);
      }
      if (getAttachmentList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(attachmentMemoizedSerializedSize);
      }
      for (int i = 0; i < attachment_.size(); i++) {
        output.writeInt32NoTag(attachment_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, time_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < attachment_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(attachment_.getInt(i));
        }
        size += dataSize;
        if (!getAttachmentList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        attachmentMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.infinity.protocol.HelloOuterClass.Hello)) {
        return super.equals(obj);
      }
      com.infinity.protocol.HelloOuterClass.Hello other = (com.infinity.protocol.HelloOuterClass.Hello) obj;

      if (getTime()
          != other.getTime()) return false;
      if (!getAttachmentList()
          .equals(other.getAttachmentList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      if (getAttachmentCount() > 0) {
        hash = (37 * hash) + ATTACHMENT_FIELD_NUMBER;
        hash = (53 * hash) + getAttachmentList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.infinity.protocol.HelloOuterClass.Hello parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.infinity.protocol.HelloOuterClass.Hello parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.infinity.protocol.HelloOuterClass.Hello parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.infinity.protocol.HelloOuterClass.Hello parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.infinity.protocol.HelloOuterClass.Hello parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.infinity.protocol.HelloOuterClass.Hello parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.infinity.protocol.HelloOuterClass.Hello parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.infinity.protocol.HelloOuterClass.Hello parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.infinity.protocol.HelloOuterClass.Hello parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.infinity.protocol.HelloOuterClass.Hello parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.infinity.protocol.HelloOuterClass.Hello parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.infinity.protocol.HelloOuterClass.Hello parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.infinity.protocol.HelloOuterClass.Hello prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.infinity.protocol.Hello}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.infinity.protocol.Hello)
        com.infinity.protocol.HelloOuterClass.HelloOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.infinity.protocol.HelloOuterClass.internal_static_com_infinity_protocol_Hello_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.infinity.protocol.HelloOuterClass.internal_static_com_infinity_protocol_Hello_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.infinity.protocol.HelloOuterClass.Hello.class, com.infinity.protocol.HelloOuterClass.Hello.Builder.class);
      }

      // Construct using com.infinity.protocol.HelloOuterClass.Hello.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        time_ = 0L;

        attachment_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.infinity.protocol.HelloOuterClass.internal_static_com_infinity_protocol_Hello_descriptor;
      }

      @java.lang.Override
      public com.infinity.protocol.HelloOuterClass.Hello getDefaultInstanceForType() {
        return com.infinity.protocol.HelloOuterClass.Hello.getDefaultInstance();
      }

      @java.lang.Override
      public com.infinity.protocol.HelloOuterClass.Hello build() {
        com.infinity.protocol.HelloOuterClass.Hello result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.infinity.protocol.HelloOuterClass.Hello buildPartial() {
        com.infinity.protocol.HelloOuterClass.Hello result = new com.infinity.protocol.HelloOuterClass.Hello(this);
        int from_bitField0_ = bitField0_;
        result.time_ = time_;
        if (((bitField0_ & 0x00000001) != 0)) {
          attachment_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.attachment_ = attachment_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.infinity.protocol.HelloOuterClass.Hello) {
          return mergeFrom((com.infinity.protocol.HelloOuterClass.Hello)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.infinity.protocol.HelloOuterClass.Hello other) {
        if (other == com.infinity.protocol.HelloOuterClass.Hello.getDefaultInstance()) return this;
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (!other.attachment_.isEmpty()) {
          if (attachment_.isEmpty()) {
            attachment_ = other.attachment_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureAttachmentIsMutable();
            attachment_.addAll(other.attachment_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.infinity.protocol.HelloOuterClass.Hello parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.infinity.protocol.HelloOuterClass.Hello) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long time_ ;
      /**
       * <pre>
       * 当前时间
       * </pre>
       *
       * <code>int64 time = 1;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <pre>
       * 当前时间
       * </pre>
       *
       * <code>int64 time = 1;</code>
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前时间
       * </pre>
       *
       * <code>int64 time = 1;</code>
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList attachment_ = emptyIntList();
      private void ensureAttachmentIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          attachment_ = mutableCopy(attachment_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * 附加信息
       * </pre>
       *
       * <code>repeated int32 attachment = 2;</code>
       */
      public java.util.List<java.lang.Integer>
          getAttachmentList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(attachment_) : attachment_;
      }
      /**
       * <pre>
       * 附加信息
       * </pre>
       *
       * <code>repeated int32 attachment = 2;</code>
       */
      public int getAttachmentCount() {
        return attachment_.size();
      }
      /**
       * <pre>
       * 附加信息
       * </pre>
       *
       * <code>repeated int32 attachment = 2;</code>
       */
      public int getAttachment(int index) {
        return attachment_.getInt(index);
      }
      /**
       * <pre>
       * 附加信息
       * </pre>
       *
       * <code>repeated int32 attachment = 2;</code>
       */
      public Builder setAttachment(
          int index, int value) {
        ensureAttachmentIsMutable();
        attachment_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 附加信息
       * </pre>
       *
       * <code>repeated int32 attachment = 2;</code>
       */
      public Builder addAttachment(int value) {
        ensureAttachmentIsMutable();
        attachment_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 附加信息
       * </pre>
       *
       * <code>repeated int32 attachment = 2;</code>
       */
      public Builder addAllAttachment(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureAttachmentIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, attachment_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 附加信息
       * </pre>
       *
       * <code>repeated int32 attachment = 2;</code>
       */
      public Builder clearAttachment() {
        attachment_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.infinity.protocol.Hello)
    }

    // @@protoc_insertion_point(class_scope:com.infinity.protocol.Hello)
    private static final com.infinity.protocol.HelloOuterClass.Hello DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.infinity.protocol.HelloOuterClass.Hello();
    }

    public static com.infinity.protocol.HelloOuterClass.Hello getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Hello>
        PARSER = new com.google.protobuf.AbstractParser<Hello>() {
      @java.lang.Override
      public Hello parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Hello(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Hello> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Hello> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.infinity.protocol.HelloOuterClass.Hello getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_infinity_protocol_Hello_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_infinity_protocol_Hello_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013hello.proto\022\025com.infinity.protocol\")\n\005" +
      "Hello\022\014\n\004time\030\001 \001(\003\022\022\n\nattachment\030\002 \003(\005b" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_infinity_protocol_Hello_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_infinity_protocol_Hello_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_infinity_protocol_Hello_descriptor,
        new java.lang.String[] { "Time", "Attachment", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
