// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: query_node_response.proto

package com.infinity.protocol;

public final class QueryNodeResponse {
  private QueryNodeResponse() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface query_node_responseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.infinity.protocol.query_node_response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 查询的节点类型
     * </pre>
     *
     * <code>string node_type = 1;</code>
     */
    java.lang.String getNodeType();
    /**
     * <pre>
     * 查询的节点类型
     * </pre>
     *
     * <code>string node_type = 1;</code>
     */
    com.google.protobuf.ByteString
        getNodeTypeBytes();

    /**
     * <pre>
     * 查询请求序列号
     * </pre>
     *
     * <code>int64 request_id = 2;</code>
     */
    long getRequestId();

    /**
     * <pre>
     * 查询结果列表，包含节点列表
     * </pre>
     *
     * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
     */
    java.util.List<com.infinity.protocol.ServerNode.server_node> 
        getNodesList();
    /**
     * <pre>
     * 查询结果列表，包含节点列表
     * </pre>
     *
     * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
     */
    com.infinity.protocol.ServerNode.server_node getNodes(int index);
    /**
     * <pre>
     * 查询结果列表，包含节点列表
     * </pre>
     *
     * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
     */
    int getNodesCount();
    /**
     * <pre>
     * 查询结果列表，包含节点列表
     * </pre>
     *
     * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
     */
    java.util.List<? extends com.infinity.protocol.ServerNode.server_nodeOrBuilder> 
        getNodesOrBuilderList();
    /**
     * <pre>
     * 查询结果列表，包含节点列表
     * </pre>
     *
     * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
     */
    com.infinity.protocol.ServerNode.server_nodeOrBuilder getNodesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.infinity.protocol.query_node_response}
   */
  public  static final class query_node_response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.infinity.protocol.query_node_response)
      query_node_responseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use query_node_response.newBuilder() to construct.
    private query_node_response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private query_node_response() {
      nodeType_ = "";
      nodes_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new query_node_response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private query_node_response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              nodeType_ = s;
              break;
            }
            case 16: {

              requestId_ = input.readInt64();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                nodes_ = new java.util.ArrayList<com.infinity.protocol.ServerNode.server_node>();
                mutable_bitField0_ |= 0x00000001;
              }
              nodes_.add(
                  input.readMessage(com.infinity.protocol.ServerNode.server_node.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          nodes_ = java.util.Collections.unmodifiableList(nodes_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.infinity.protocol.QueryNodeResponse.internal_static_com_infinity_protocol_query_node_response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.infinity.protocol.QueryNodeResponse.internal_static_com_infinity_protocol_query_node_response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.infinity.protocol.QueryNodeResponse.query_node_response.class, com.infinity.protocol.QueryNodeResponse.query_node_response.Builder.class);
    }

    public static final int NODE_TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object nodeType_;
    /**
     * <pre>
     * 查询的节点类型
     * </pre>
     *
     * <code>string node_type = 1;</code>
     */
    public java.lang.String getNodeType() {
      java.lang.Object ref = nodeType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 查询的节点类型
     * </pre>
     *
     * <code>string node_type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNodeTypeBytes() {
      java.lang.Object ref = nodeType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUEST_ID_FIELD_NUMBER = 2;
    private long requestId_;
    /**
     * <pre>
     * 查询请求序列号
     * </pre>
     *
     * <code>int64 request_id = 2;</code>
     */
    public long getRequestId() {
      return requestId_;
    }

    public static final int NODES_FIELD_NUMBER = 3;
    private java.util.List<com.infinity.protocol.ServerNode.server_node> nodes_;
    /**
     * <pre>
     * 查询结果列表，包含节点列表
     * </pre>
     *
     * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
     */
    public java.util.List<com.infinity.protocol.ServerNode.server_node> getNodesList() {
      return nodes_;
    }
    /**
     * <pre>
     * 查询结果列表，包含节点列表
     * </pre>
     *
     * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
     */
    public java.util.List<? extends com.infinity.protocol.ServerNode.server_nodeOrBuilder> 
        getNodesOrBuilderList() {
      return nodes_;
    }
    /**
     * <pre>
     * 查询结果列表，包含节点列表
     * </pre>
     *
     * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
     */
    public int getNodesCount() {
      return nodes_.size();
    }
    /**
     * <pre>
     * 查询结果列表，包含节点列表
     * </pre>
     *
     * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
     */
    public com.infinity.protocol.ServerNode.server_node getNodes(int index) {
      return nodes_.get(index);
    }
    /**
     * <pre>
     * 查询结果列表，包含节点列表
     * </pre>
     *
     * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
     */
    public com.infinity.protocol.ServerNode.server_nodeOrBuilder getNodesOrBuilder(
        int index) {
      return nodes_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNodeTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nodeType_);
      }
      if (requestId_ != 0L) {
        output.writeInt64(2, requestId_);
      }
      for (int i = 0; i < nodes_.size(); i++) {
        output.writeMessage(3, nodes_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNodeTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nodeType_);
      }
      if (requestId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, requestId_);
      }
      for (int i = 0; i < nodes_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, nodes_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.infinity.protocol.QueryNodeResponse.query_node_response)) {
        return super.equals(obj);
      }
      com.infinity.protocol.QueryNodeResponse.query_node_response other = (com.infinity.protocol.QueryNodeResponse.query_node_response) obj;

      if (!getNodeType()
          .equals(other.getNodeType())) return false;
      if (getRequestId()
          != other.getRequestId()) return false;
      if (!getNodesList()
          .equals(other.getNodesList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NODE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getNodeType().hashCode();
      hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestId());
      if (getNodesCount() > 0) {
        hash = (37 * hash) + NODES_FIELD_NUMBER;
        hash = (53 * hash) + getNodesList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.infinity.protocol.QueryNodeResponse.query_node_response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.infinity.protocol.QueryNodeResponse.query_node_response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.infinity.protocol.QueryNodeResponse.query_node_response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.infinity.protocol.QueryNodeResponse.query_node_response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.infinity.protocol.QueryNodeResponse.query_node_response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.infinity.protocol.QueryNodeResponse.query_node_response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.infinity.protocol.QueryNodeResponse.query_node_response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.infinity.protocol.QueryNodeResponse.query_node_response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.infinity.protocol.QueryNodeResponse.query_node_response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.infinity.protocol.QueryNodeResponse.query_node_response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.infinity.protocol.QueryNodeResponse.query_node_response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.infinity.protocol.QueryNodeResponse.query_node_response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.infinity.protocol.QueryNodeResponse.query_node_response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.infinity.protocol.query_node_response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.infinity.protocol.query_node_response)
        com.infinity.protocol.QueryNodeResponse.query_node_responseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.infinity.protocol.QueryNodeResponse.internal_static_com_infinity_protocol_query_node_response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.infinity.protocol.QueryNodeResponse.internal_static_com_infinity_protocol_query_node_response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.infinity.protocol.QueryNodeResponse.query_node_response.class, com.infinity.protocol.QueryNodeResponse.query_node_response.Builder.class);
      }

      // Construct using com.infinity.protocol.QueryNodeResponse.query_node_response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getNodesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nodeType_ = "";

        requestId_ = 0L;

        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          nodesBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.infinity.protocol.QueryNodeResponse.internal_static_com_infinity_protocol_query_node_response_descriptor;
      }

      @java.lang.Override
      public com.infinity.protocol.QueryNodeResponse.query_node_response getDefaultInstanceForType() {
        return com.infinity.protocol.QueryNodeResponse.query_node_response.getDefaultInstance();
      }

      @java.lang.Override
      public com.infinity.protocol.QueryNodeResponse.query_node_response build() {
        com.infinity.protocol.QueryNodeResponse.query_node_response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.infinity.protocol.QueryNodeResponse.query_node_response buildPartial() {
        com.infinity.protocol.QueryNodeResponse.query_node_response result = new com.infinity.protocol.QueryNodeResponse.query_node_response(this);
        int from_bitField0_ = bitField0_;
        result.nodeType_ = nodeType_;
        result.requestId_ = requestId_;
        if (nodesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            nodes_ = java.util.Collections.unmodifiableList(nodes_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.nodes_ = nodes_;
        } else {
          result.nodes_ = nodesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.infinity.protocol.QueryNodeResponse.query_node_response) {
          return mergeFrom((com.infinity.protocol.QueryNodeResponse.query_node_response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.infinity.protocol.QueryNodeResponse.query_node_response other) {
        if (other == com.infinity.protocol.QueryNodeResponse.query_node_response.getDefaultInstance()) return this;
        if (!other.getNodeType().isEmpty()) {
          nodeType_ = other.nodeType_;
          onChanged();
        }
        if (other.getRequestId() != 0L) {
          setRequestId(other.getRequestId());
        }
        if (nodesBuilder_ == null) {
          if (!other.nodes_.isEmpty()) {
            if (nodes_.isEmpty()) {
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureNodesIsMutable();
              nodes_.addAll(other.nodes_);
            }
            onChanged();
          }
        } else {
          if (!other.nodes_.isEmpty()) {
            if (nodesBuilder_.isEmpty()) {
              nodesBuilder_.dispose();
              nodesBuilder_ = null;
              nodes_ = other.nodes_;
              bitField0_ = (bitField0_ & ~0x00000001);
              nodesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getNodesFieldBuilder() : null;
            } else {
              nodesBuilder_.addAllMessages(other.nodes_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.infinity.protocol.QueryNodeResponse.query_node_response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.infinity.protocol.QueryNodeResponse.query_node_response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object nodeType_ = "";
      /**
       * <pre>
       * 查询的节点类型
       * </pre>
       *
       * <code>string node_type = 1;</code>
       */
      public java.lang.String getNodeType() {
        java.lang.Object ref = nodeType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nodeType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 查询的节点类型
       * </pre>
       *
       * <code>string node_type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNodeTypeBytes() {
        java.lang.Object ref = nodeType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 查询的节点类型
       * </pre>
       *
       * <code>string node_type = 1;</code>
       */
      public Builder setNodeType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nodeType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 查询的节点类型
       * </pre>
       *
       * <code>string node_type = 1;</code>
       */
      public Builder clearNodeType() {
        
        nodeType_ = getDefaultInstance().getNodeType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 查询的节点类型
       * </pre>
       *
       * <code>string node_type = 1;</code>
       */
      public Builder setNodeTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nodeType_ = value;
        onChanged();
        return this;
      }

      private long requestId_ ;
      /**
       * <pre>
       * 查询请求序列号
       * </pre>
       *
       * <code>int64 request_id = 2;</code>
       */
      public long getRequestId() {
        return requestId_;
      }
      /**
       * <pre>
       * 查询请求序列号
       * </pre>
       *
       * <code>int64 request_id = 2;</code>
       */
      public Builder setRequestId(long value) {
        
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 查询请求序列号
       * </pre>
       *
       * <code>int64 request_id = 2;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<com.infinity.protocol.ServerNode.server_node> nodes_ =
        java.util.Collections.emptyList();
      private void ensureNodesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          nodes_ = new java.util.ArrayList<com.infinity.protocol.ServerNode.server_node>(nodes_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.infinity.protocol.ServerNode.server_node, com.infinity.protocol.ServerNode.server_node.Builder, com.infinity.protocol.ServerNode.server_nodeOrBuilder> nodesBuilder_;

      /**
       * <pre>
       * 查询结果列表，包含节点列表
       * </pre>
       *
       * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
       */
      public java.util.List<com.infinity.protocol.ServerNode.server_node> getNodesList() {
        if (nodesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(nodes_);
        } else {
          return nodesBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 查询结果列表，包含节点列表
       * </pre>
       *
       * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
       */
      public int getNodesCount() {
        if (nodesBuilder_ == null) {
          return nodes_.size();
        } else {
          return nodesBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 查询结果列表，包含节点列表
       * </pre>
       *
       * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
       */
      public com.infinity.protocol.ServerNode.server_node getNodes(int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);
        } else {
          return nodesBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 查询结果列表，包含节点列表
       * </pre>
       *
       * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
       */
      public Builder setNodes(
          int index, com.infinity.protocol.ServerNode.server_node value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.set(index, value);
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 查询结果列表，包含节点列表
       * </pre>
       *
       * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
       */
      public Builder setNodes(
          int index, com.infinity.protocol.ServerNode.server_node.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.set(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 查询结果列表，包含节点列表
       * </pre>
       *
       * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
       */
      public Builder addNodes(com.infinity.protocol.ServerNode.server_node value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 查询结果列表，包含节点列表
       * </pre>
       *
       * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
       */
      public Builder addNodes(
          int index, com.infinity.protocol.ServerNode.server_node value) {
        if (nodesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureNodesIsMutable();
          nodes_.add(index, value);
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 查询结果列表，包含节点列表
       * </pre>
       *
       * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
       */
      public Builder addNodes(
          com.infinity.protocol.ServerNode.server_node.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 查询结果列表，包含节点列表
       * </pre>
       *
       * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
       */
      public Builder addNodes(
          int index, com.infinity.protocol.ServerNode.server_node.Builder builderForValue) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.add(index, builderForValue.build());
          onChanged();
        } else {
          nodesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 查询结果列表，包含节点列表
       * </pre>
       *
       * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
       */
      public Builder addAllNodes(
          java.lang.Iterable<? extends com.infinity.protocol.ServerNode.server_node> values) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, nodes_);
          onChanged();
        } else {
          nodesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 查询结果列表，包含节点列表
       * </pre>
       *
       * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
       */
      public Builder clearNodes() {
        if (nodesBuilder_ == null) {
          nodes_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          nodesBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 查询结果列表，包含节点列表
       * </pre>
       *
       * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
       */
      public Builder removeNodes(int index) {
        if (nodesBuilder_ == null) {
          ensureNodesIsMutable();
          nodes_.remove(index);
          onChanged();
        } else {
          nodesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 查询结果列表，包含节点列表
       * </pre>
       *
       * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
       */
      public com.infinity.protocol.ServerNode.server_node.Builder getNodesBuilder(
          int index) {
        return getNodesFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 查询结果列表，包含节点列表
       * </pre>
       *
       * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
       */
      public com.infinity.protocol.ServerNode.server_nodeOrBuilder getNodesOrBuilder(
          int index) {
        if (nodesBuilder_ == null) {
          return nodes_.get(index);  } else {
          return nodesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 查询结果列表，包含节点列表
       * </pre>
       *
       * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
       */
      public java.util.List<? extends com.infinity.protocol.ServerNode.server_nodeOrBuilder> 
           getNodesOrBuilderList() {
        if (nodesBuilder_ != null) {
          return nodesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(nodes_);
        }
      }
      /**
       * <pre>
       * 查询结果列表，包含节点列表
       * </pre>
       *
       * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
       */
      public com.infinity.protocol.ServerNode.server_node.Builder addNodesBuilder() {
        return getNodesFieldBuilder().addBuilder(
            com.infinity.protocol.ServerNode.server_node.getDefaultInstance());
      }
      /**
       * <pre>
       * 查询结果列表，包含节点列表
       * </pre>
       *
       * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
       */
      public com.infinity.protocol.ServerNode.server_node.Builder addNodesBuilder(
          int index) {
        return getNodesFieldBuilder().addBuilder(
            index, com.infinity.protocol.ServerNode.server_node.getDefaultInstance());
      }
      /**
       * <pre>
       * 查询结果列表，包含节点列表
       * </pre>
       *
       * <code>repeated .com.infinity.protocol.server_node nodes = 3;</code>
       */
      public java.util.List<com.infinity.protocol.ServerNode.server_node.Builder> 
           getNodesBuilderList() {
        return getNodesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.infinity.protocol.ServerNode.server_node, com.infinity.protocol.ServerNode.server_node.Builder, com.infinity.protocol.ServerNode.server_nodeOrBuilder> 
          getNodesFieldBuilder() {
        if (nodesBuilder_ == null) {
          nodesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.infinity.protocol.ServerNode.server_node, com.infinity.protocol.ServerNode.server_node.Builder, com.infinity.protocol.ServerNode.server_nodeOrBuilder>(
                  nodes_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          nodes_ = null;
        }
        return nodesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.infinity.protocol.query_node_response)
    }

    // @@protoc_insertion_point(class_scope:com.infinity.protocol.query_node_response)
    private static final com.infinity.protocol.QueryNodeResponse.query_node_response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.infinity.protocol.QueryNodeResponse.query_node_response();
    }

    public static com.infinity.protocol.QueryNodeResponse.query_node_response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<query_node_response>
        PARSER = new com.google.protobuf.AbstractParser<query_node_response>() {
      @java.lang.Override
      public query_node_response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new query_node_response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<query_node_response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<query_node_response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.infinity.protocol.QueryNodeResponse.query_node_response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_infinity_protocol_query_node_response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_infinity_protocol_query_node_response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031query_node_response.proto\022\025com.infinit" +
      "y.protocol\032\021server_node.proto\"o\n\023query_n" +
      "ode_response\022\021\n\tnode_type\030\001 \001(\t\022\022\n\nreque" +
      "st_id\030\002 \001(\003\0221\n\005nodes\030\003 \003(\0132\".com.infinit" +
      "y.protocol.server_nodeb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.infinity.protocol.ServerNode.getDescriptor(),
        });
    internal_static_com_infinity_protocol_query_node_response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_infinity_protocol_query_node_response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_infinity_protocol_query_node_response_descriptor,
        new java.lang.String[] { "NodeType", "RequestId", "Nodes", });
    com.infinity.protocol.ServerNode.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
