// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: query_node_request.proto

package com.infinity.protocol;

public final class QueryNodeRequest {
  private QueryNodeRequest() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface query_node_requestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.infinity.protocol.query_node_request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 查询的节点类型
     * </pre>
     *
     * <code>string node_type = 1;</code>
     */
    java.lang.String getNodeType();
    /**
     * <pre>
     * 查询的节点类型
     * </pre>
     *
     * <code>string node_type = 1;</code>
     */
    com.google.protobuf.ByteString
        getNodeTypeBytes();

    /**
     * <pre>
     * 查询请求序列号
     * </pre>
     *
     * <code>int64 request_id = 2;</code>
     */
    long getRequestId();
  }
  /**
   * Protobuf type {@code com.infinity.protocol.query_node_request}
   */
  public  static final class query_node_request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.infinity.protocol.query_node_request)
      query_node_requestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use query_node_request.newBuilder() to construct.
    private query_node_request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private query_node_request() {
      nodeType_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new query_node_request();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private query_node_request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              nodeType_ = s;
              break;
            }
            case 16: {

              requestId_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.infinity.protocol.QueryNodeRequest.internal_static_com_infinity_protocol_query_node_request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.infinity.protocol.QueryNodeRequest.internal_static_com_infinity_protocol_query_node_request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.infinity.protocol.QueryNodeRequest.query_node_request.class, com.infinity.protocol.QueryNodeRequest.query_node_request.Builder.class);
    }

    public static final int NODE_TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object nodeType_;
    /**
     * <pre>
     * 查询的节点类型
     * </pre>
     *
     * <code>string node_type = 1;</code>
     */
    public java.lang.String getNodeType() {
      java.lang.Object ref = nodeType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nodeType_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 查询的节点类型
     * </pre>
     *
     * <code>string node_type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNodeTypeBytes() {
      java.lang.Object ref = nodeType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nodeType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUEST_ID_FIELD_NUMBER = 2;
    private long requestId_;
    /**
     * <pre>
     * 查询请求序列号
     * </pre>
     *
     * <code>int64 request_id = 2;</code>
     */
    public long getRequestId() {
      return requestId_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNodeTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, nodeType_);
      }
      if (requestId_ != 0L) {
        output.writeInt64(2, requestId_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNodeTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, nodeType_);
      }
      if (requestId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, requestId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.infinity.protocol.QueryNodeRequest.query_node_request)) {
        return super.equals(obj);
      }
      com.infinity.protocol.QueryNodeRequest.query_node_request other = (com.infinity.protocol.QueryNodeRequest.query_node_request) obj;

      if (!getNodeType()
          .equals(other.getNodeType())) return false;
      if (getRequestId()
          != other.getRequestId()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NODE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getNodeType().hashCode();
      hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRequestId());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.infinity.protocol.QueryNodeRequest.query_node_request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.infinity.protocol.QueryNodeRequest.query_node_request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.infinity.protocol.QueryNodeRequest.query_node_request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.infinity.protocol.QueryNodeRequest.query_node_request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.infinity.protocol.QueryNodeRequest.query_node_request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.infinity.protocol.QueryNodeRequest.query_node_request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.infinity.protocol.QueryNodeRequest.query_node_request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.infinity.protocol.QueryNodeRequest.query_node_request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.infinity.protocol.QueryNodeRequest.query_node_request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.infinity.protocol.QueryNodeRequest.query_node_request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.infinity.protocol.QueryNodeRequest.query_node_request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.infinity.protocol.QueryNodeRequest.query_node_request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.infinity.protocol.QueryNodeRequest.query_node_request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.infinity.protocol.query_node_request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.infinity.protocol.query_node_request)
        com.infinity.protocol.QueryNodeRequest.query_node_requestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.infinity.protocol.QueryNodeRequest.internal_static_com_infinity_protocol_query_node_request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.infinity.protocol.QueryNodeRequest.internal_static_com_infinity_protocol_query_node_request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.infinity.protocol.QueryNodeRequest.query_node_request.class, com.infinity.protocol.QueryNodeRequest.query_node_request.Builder.class);
      }

      // Construct using com.infinity.protocol.QueryNodeRequest.query_node_request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        nodeType_ = "";

        requestId_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.infinity.protocol.QueryNodeRequest.internal_static_com_infinity_protocol_query_node_request_descriptor;
      }

      @java.lang.Override
      public com.infinity.protocol.QueryNodeRequest.query_node_request getDefaultInstanceForType() {
        return com.infinity.protocol.QueryNodeRequest.query_node_request.getDefaultInstance();
      }

      @java.lang.Override
      public com.infinity.protocol.QueryNodeRequest.query_node_request build() {
        com.infinity.protocol.QueryNodeRequest.query_node_request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.infinity.protocol.QueryNodeRequest.query_node_request buildPartial() {
        com.infinity.protocol.QueryNodeRequest.query_node_request result = new com.infinity.protocol.QueryNodeRequest.query_node_request(this);
        result.nodeType_ = nodeType_;
        result.requestId_ = requestId_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.infinity.protocol.QueryNodeRequest.query_node_request) {
          return mergeFrom((com.infinity.protocol.QueryNodeRequest.query_node_request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.infinity.protocol.QueryNodeRequest.query_node_request other) {
        if (other == com.infinity.protocol.QueryNodeRequest.query_node_request.getDefaultInstance()) return this;
        if (!other.getNodeType().isEmpty()) {
          nodeType_ = other.nodeType_;
          onChanged();
        }
        if (other.getRequestId() != 0L) {
          setRequestId(other.getRequestId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.infinity.protocol.QueryNodeRequest.query_node_request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.infinity.protocol.QueryNodeRequest.query_node_request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object nodeType_ = "";
      /**
       * <pre>
       * 查询的节点类型
       * </pre>
       *
       * <code>string node_type = 1;</code>
       */
      public java.lang.String getNodeType() {
        java.lang.Object ref = nodeType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nodeType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 查询的节点类型
       * </pre>
       *
       * <code>string node_type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNodeTypeBytes() {
        java.lang.Object ref = nodeType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nodeType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 查询的节点类型
       * </pre>
       *
       * <code>string node_type = 1;</code>
       */
      public Builder setNodeType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nodeType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 查询的节点类型
       * </pre>
       *
       * <code>string node_type = 1;</code>
       */
      public Builder clearNodeType() {
        
        nodeType_ = getDefaultInstance().getNodeType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 查询的节点类型
       * </pre>
       *
       * <code>string node_type = 1;</code>
       */
      public Builder setNodeTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nodeType_ = value;
        onChanged();
        return this;
      }

      private long requestId_ ;
      /**
       * <pre>
       * 查询请求序列号
       * </pre>
       *
       * <code>int64 request_id = 2;</code>
       */
      public long getRequestId() {
        return requestId_;
      }
      /**
       * <pre>
       * 查询请求序列号
       * </pre>
       *
       * <code>int64 request_id = 2;</code>
       */
      public Builder setRequestId(long value) {
        
        requestId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 查询请求序列号
       * </pre>
       *
       * <code>int64 request_id = 2;</code>
       */
      public Builder clearRequestId() {
        
        requestId_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.infinity.protocol.query_node_request)
    }

    // @@protoc_insertion_point(class_scope:com.infinity.protocol.query_node_request)
    private static final com.infinity.protocol.QueryNodeRequest.query_node_request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.infinity.protocol.QueryNodeRequest.query_node_request();
    }

    public static com.infinity.protocol.QueryNodeRequest.query_node_request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<query_node_request>
        PARSER = new com.google.protobuf.AbstractParser<query_node_request>() {
      @java.lang.Override
      public query_node_request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new query_node_request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<query_node_request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<query_node_request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.infinity.protocol.QueryNodeRequest.query_node_request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_infinity_protocol_query_node_request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_infinity_protocol_query_node_request_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030query_node_request.proto\022\025com.infinity" +
      ".protocol\";\n\022query_node_request\022\021\n\tnode_" +
      "type\030\001 \001(\t\022\022\n\nrequest_id\030\002 \001(\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_infinity_protocol_query_node_request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_infinity_protocol_query_node_request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_infinity_protocol_query_node_request_descriptor,
        new java.lang.String[] { "NodeType", "RequestId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
